import type { WalletConnection } from './wallet';

export const LOCAL_PROVER_URL = 'http://localhost:6300';
export const PROVING_PREFERENCE_STORAGE_KEY = 'tacitpay.proving.preference.v1';
export const CUSTOM_PROVER_URL_STORAGE_KEY = 'tacitpay.proving.custom-url.v1';

export const PROVING_TIERS = ['wallet', 'local', 'custom'] as const;
export type ProvingTier = (typeof PROVING_TIERS)[number];
export type ProvingPreference = 'auto' | ProvingTier;

export const PROVING_TIER_EXPLANATIONS: Record<ProvingTier, string> = {
  wallet: 'Proofs are generated in your wallet, so nothing leaves your browser.',
  local: 'Proofs are generated by a server on this machine, so invoice data stays on your machine.',
  custom: 'Proofs are sent to the prover server you control.',
};

export const PROVING_TIER_LABELS: Record<ProvingTier, string> = {
  wallet: 'In wallet',
  local: 'Local server',
  custom: 'Your own server',
};

export interface ProverHealth {
  status: 'available' | 'unreachable';
  url: string;
  detail: string;
  statusCode?: number;
}

interface TierAvailability {
  available: boolean;
  detail: string;
  url?: string;
}

export interface ProvingResolution {
  effectiveTier: ProvingTier | null;
  effectiveUrl?: string;
  reason: string;
  preferredTier: ProvingTier;
  preferredUnavailable: boolean;
  preferredUnavailableReason?: string;
  checkedTiers: Partial<Record<ProvingTier, TierAvailability>>;
}

export type CustomProverUrlValidation =
  { valid: true; url: string } | { valid: false; error: string };

function safeStorage(): Storage | undefined {
  if (typeof window === 'undefined') return undefined;
  try {
    return window.localStorage;
  } catch {
    return undefined;
  }
}

export function validateCustomProverUrl(value: string): CustomProverUrlValidation {
  const input = value.trim();
  if (!input) return { valid: false, error: 'Enter the URL of a prover server you control.' };

  let url: URL;
  try {
    url = new URL(input);
  } catch {
    return { valid: false, error: 'Enter a complete URL, including https://.' };
  }

  if (url.username || url.password) {
    return { valid: false, error: 'Do not include credentials in the prover URL.' };
  }

  const isLoopback = url.hostname === 'localhost' || url.hostname === '127.0.0.1';
  if (url.protocol !== 'https:' && !(url.protocol === 'http:' && isLoopback)) {
    return {
      valid: false,
      error: 'Use https://. Plain http:// is allowed only for localhost or 127.0.0.1.',
    };
  }

  return { valid: true, url: url.href.replace(/\/$/u, '') };
}

export function getStoredProvingPreference(): ProvingPreference {
  try {
    const saved = safeStorage()?.getItem(PROVING_PREFERENCE_STORAGE_KEY);
    return saved === 'wallet' || saved === 'local' || saved === 'custom' ? saved : 'auto';
  } catch {
    return 'auto';
  }
}

export function storeProvingPreference(preference: ProvingPreference): void {
  try {
    safeStorage()?.setItem(PROVING_PREFERENCE_STORAGE_KEY, preference);
  } catch {
    // The selection remains session-only when browser storage is unavailable.
  }
}

export function getStoredCustomProverUrl(): string {
  try {
    const saved = safeStorage()?.getItem(CUSTOM_PROVER_URL_STORAGE_KEY) ?? '';
    const validation = validateCustomProverUrl(saved);
    return validation.valid ? validation.url : '';
  } catch {
    return '';
  }
}

export function storeCustomProverUrl(value: string): CustomProverUrlValidation {
  const validation = validateCustomProverUrl(value);
  if (!validation.valid) return validation;
  try {
    safeStorage()?.setItem(CUSTOM_PROVER_URL_STORAGE_KEY, validation.url);
  } catch {
    // The validated URL remains session-only when browser storage is unavailable.
  }
  return validation;
}

export function clearStoredCustomProverUrl(): void {
  try {
    safeStorage()?.removeItem(CUSTOM_PROVER_URL_STORAGE_KEY);
  } catch {
    // The in-memory setting can still be cleared when browser storage is unavailable.
  }
}

export function hasWalletProvingProvider(connection: WalletConnection | null): boolean {
  if (!connection) return false;
  try {
    return typeof Reflect.get(connection.api, 'getProvingProvider') === 'function';
  } catch {
    return false;
  }
}

export function getWalletProvingCapability(connection: WalletConnection): string {
  return hasWalletProvingProvider(connection)
    ? 'Proves in browser — no extra setup'
    : 'Needs a local proof server';
}

export async function checkProverHealth(
  baseUrl: string,
  timeoutMilliseconds = 2500,
): Promise<ProverHealth> {
  const controller = new AbortController();
  const timeout = window.setTimeout(() => controller.abort(), timeoutMilliseconds);

  try {
    const response = await fetch(baseUrl, {
      method: 'GET',
      cache: 'no-store',
      headers: { Accept: 'application/json, text/plain, */*' },
      signal: controller.signal,
    });
    if (!response.ok) {
      return {
        status: 'unreachable',
        url: baseUrl,
        detail: `The prover returned HTTP ${response.status}.`,
        statusCode: response.status,
      };
    }
    return {
      status: 'available',
      url: baseUrl,
      detail: `Available · HTTP ${response.status}`,
      statusCode: response.status,
    };
  } catch (error) {
    return {
      status: 'unreachable',
      url: baseUrl,
      detail:
        error instanceof DOMException && error.name === 'AbortError'
          ? 'The prover did not respond before the health check timed out.'
          : 'The prover could not be reached from this browser.',
    };
  } finally {
    window.clearTimeout(timeout);
  }
}

function preferredTierFor(preference: ProvingPreference): ProvingTier {
  return preference === 'auto' ? 'wallet' : preference;
}

function resolutionOrder(preference: ProvingPreference): ProvingTier[] {
  if (preference === 'auto') return [...PROVING_TIERS];
  return [preference, ...PROVING_TIERS.filter((tier) => tier !== preference)];
}

async function checkTier(
  tier: ProvingTier,
  connection: WalletConnection | null,
  customUrl: string,
): Promise<TierAvailability> {
  if (tier === 'wallet') {
    return hasWalletProvingProvider(connection)
      ? { available: true, detail: 'The connected wallet provides in-browser proving.' }
      : {
          available: false,
          detail: connection
            ? 'The connected wallet does not expose getProvingProvider().'
            : 'Connect a wallet to check for in-browser proving.',
        };
  }

  const url = tier === 'local' ? LOCAL_PROVER_URL : customUrl;
  if (tier === 'custom') {
    const validation = validateCustomProverUrl(url);
    if (!validation.valid) return { available: false, detail: validation.error };
  }

  const health = await checkProverHealth(url);
  return { available: health.status === 'available', detail: health.detail, url };
}

function describeResolution(
  preference: ProvingPreference,
  effectiveTier: ProvingTier | null,
  preferredUnavailable: boolean,
): string {
  if (!effectiveTier) {
    return 'No proving option is available. Choose or configure one in Settings.';
  }
  if (preference === 'auto') {
    if (effectiveTier === 'wallet') {
      return 'Auto selected in-wallet proving because the connected wallet provides it.';
    }
    if (effectiveTier === 'local') {
      return 'Auto selected the local server because in-wallet proving is unavailable.';
    }
    return 'Auto selected your server because in-wallet proving and the local server are unavailable.';
  }
  if (!preferredUnavailable) {
    return `Using ${PROVING_TIER_LABELS[effectiveTier].toLowerCase()} as selected.`;
  }
  return `${PROVING_TIER_LABELS[preference]} is unavailable, so ${PROVING_TIER_LABELS[
    effectiveTier
  ].toLowerCase()} will be used instead.`;
}

export async function resolveProvingTier(
  connection: WalletConnection | null,
  preference: ProvingPreference,
  customUrl = getStoredCustomProverUrl(),
): Promise<ProvingResolution> {
  const order = resolutionOrder(preference);
  const preferredTier = preferredTierFor(preference);
  const checkedTiers: Partial<Record<ProvingTier, TierAvailability>> = {};
  let effectiveTier: ProvingTier | null = null;

  for (const tier of order) {
    const availability = await checkTier(tier, connection, customUrl);
    checkedTiers[tier] = availability;
    if (availability.available) {
      effectiveTier = tier;
      break;
    }
  }

  const preferredAvailability = checkedTiers[preferredTier];
  const preferredUnavailable = preferredAvailability?.available === false;
  return {
    effectiveTier,
    effectiveUrl:
      effectiveTier === 'local'
        ? LOCAL_PROVER_URL
        : effectiveTier === 'custom'
          ? customUrl
          : undefined,
    reason: describeResolution(preference, effectiveTier, preferredUnavailable),
    preferredTier,
    preferredUnavailable,
    preferredUnavailableReason: preferredUnavailable ? preferredAvailability.detail : undefined,
    checkedTiers,
  };
}

export function getProvingDisplayLabel(resolution: ProvingResolution | null): string {
  if (!resolution?.effectiveTier) return 'Unavailable';
  if (resolution.effectiveTier !== 'custom' || !resolution.effectiveUrl) {
    return PROVING_TIER_LABELS[resolution.effectiveTier];
  }
  try {
    return `Your server (${new URL(resolution.effectiveUrl).host})`;
  } catch {
    return PROVING_TIER_LABELS.custom;
  }
}
